stages:
  - build
  - test
  - deploy

variables:
  CI_IMAGE:                        "paritytech/tools:latest"
  TEST_GLOBAL_VAR:                 "lalala"

default:
  image:                           $CI_IMAGE
  retry:
    max: 2
    when:
      - runner_system_failure
      - unknown_failure
      - api_failure
  interruptible:                   true
  tags:
    - testlab-docker

.test-refs:                        &test-refs
  rules:
    - if: $CI_PIPELINE_SOURCE == "web"
    - if: $CI_PIPELINE_SOURCE == "schedule"
    - if: $CI_COMMIT_REF_NAME == "master"
    - if: $CI_COMMIT_REF_NAME =~ /^[0-9]+$/                         # PRs
    - if: $CI_COMMIT_REF_NAME =~ /^some-release-v[0-9]+\.[0-9]+.*$/              # i.e. some-release-v1.0, some-release-v2.1rc1

build-job:
  stage:                           build
  <<:                              *test-refs
  variables:
    TEST_LOCAL_VAR:                "ololo"
  script:
    - echo $TEST_GLOBAL_VAR
    - echo $TEST_LOCAL_VAR
    - export PRNUM=$CI_COMMIT_BRANCH
    - export BRANCHNAME=$(curl -s https://api.github.com/repos/tripleightech/alvicsam-playground/pulls/$PRNUM | jq '.head.ref')
    - echo $BRANCHNAME

